security:
    # Password hashers configuration
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Veterinarian: 'auto'
        App\Entity\Owner: 'auto'

    # Providers configuration
    providers:
        veterinarian_provider:
            entity:
                class: App\Entity\Veterinarian
                property: mail

        owner_provider:
            entity:
                class: App\Entity\Owner
                property: mail

    # Firewalls configuration
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: veterinarian_provider  # Default provider (can be omitted if not needed)
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout

        veterinarian:
            pattern: ^/veterinarian
            provider: veterinarian_provider
            form_login:
                login_path: veterinarian_login
                check_path: veterinarian_login
            logout:
                path: veterinarian_logout

        owner:
            pattern: ^/owner
            provider: owner_provider
            form_login:
                login_path: owner_login
                check_path: owner_login
            logout:
                path: owner_logout

    # Access control configuration
    access_control:
        - { path: ^/veterinarian, roles: ROLE_VETERINARIAN }
        - { path: ^/owner, roles: ROLE_OWNER }
